export const ADD_FACILITIES='ADD_FACILITIES'

export const DELETE='DELETE'
export const EDIT='EDIT'
export const SET_LOADING='SET_LOADING'
export const GET_FACILITIES='GET_FACILITIES'
export const GET_PRODUCT='GET_PRODUCT'