export const ADD_FACILITIES='ADD_FACILITIES'
export const DELETE='DELETE'
export const EDIT='EDIT'
export const SET_LOADING='SET_LOADING'
export const GET_FACILITIES='GET_FACILITIES'
export const GET_PRODUCT='GET_PRODUCT'

export const ADD_PRODUCT='ADD_PRODUCT'
export const DELETE_PRODUCT='DELETE_PRODUCT'
export const EDIT_PRODUCT='EDIT_PRODUCT'
export const LOADING_PRODUCT='LOADING_PRODUCT'
export const ERROR_PRODUCT='ERROR_PRODUCT'
export const ADD_REVIEW='ADD_REVIEW'
export const GET_REVIEW='GET_REVIEW'

export const ADD_TO_CART='ADD_TO_CART'
export const GET_CART_DATA='GET_CART_DATA'

export const ADD_CATEGORY='ADD_CATEGORY'
export const DELETE_CATEGORY=' DELETE_CATEGORY'
export const EDIT_CATEGORY='EDIT_CATEGORY'
export const GET_CATEGORY='GET_CATEGORY'

// export const ADD_SUBCATEGORY='ADD_SUBCATEGORY'
// export const DELETE_SUBCATEGORY=' DELETE_SUBCATEGORY'
// export const EDIT_SUBCATEGORY='EDIT_SUBCATEGORY'
// export const GET_SUBCATEGORY='GET_SUBCATEGORY'



