export const TOOGLE_THEM=' TOOGLE_THEM'


export const CONTACT_GET='CONTACT_GET';

export const CONTACT_ADD='CONTACT_ADD';

export const CONTACT_UPDATE='CONTACT_UPDATE';

export const CONTACT_REMOVE='CONTACT_REMOVE';